_target_: src.model.LIUNet3DMKIRECAC3TriMambaBottleneck
in_channels: 4
out_channels: 3
encoder_branch_filters: [4, 8, 16, 32]
inception_kernel_sizes: [1, 3, 5]
mkir_expansion_ratio: 4
mkir_activation: relu6
upsample_mode: nearest
mamba_state: 16
mamba_conv: 4
mamba_expand: 2
use_channel_shuffle: true
