defaults:
  - liunet_cached_ep100_ultrafast
  - override transforms: brats23_cached_gligan_real_otf
  - _self_

writer:
  run_name: liunet_cached_ep100_ultrafast_96_gligan_real_otf

dataloader:
  persistent_workers: true
  multiprocessing_context: spawn
